### PR TITLE
Add a Note for Benchmarks' Profiles in `README`

### PR DESCRIPTION
**Pull request by tareknaser**
Resolves https://github.com/ARK-Builders/ark-rust/issues/40
Related issue: ARK-Builders/arklib#30

### CODE REVIEW

**Comment by kirillt** [comment]
@tareknaser have you encountered this error?
```
...
    Finished bench [optimized + debuginfo] target(s) in 32.70s

dtrace: system integrity protection is on, some features will not be available
dtrace: failed to initialize dtrace: DTrace requires additional privileges

failed to sample program
```

1. I guess, the privileges problem can be worked around by using `sudo`. Although that's not great solution.
2. What is system integrity in `dtrace`?

**Comment by tareknaser** [comment]
I've noticed the same problem on my Mac. 

Found this information online:
"On all current MacOS versions, System Integrity Protection (`SIP`) is enabled by default and prevents most uses of `dtrace` and other tools and scripts based on it (i.e. `dtruss`)"

**Comment by kirillt** [comment]
@tareknaser so if I understand correctly, benchmarking on macOS is only possible after restarting in recovery mode...

image

**Comment by kirillt** [comment]
@tareknaser could you add a note about this into README, too?

**Comment by kirillt** [comment]
@tareknaser it seems there is another recipe which allows to restart in recovery mode only once: https://forums.developer.apple.com/forums/thread/17452

Could you validate this instruction?

**Review by kirillt — APPROVED** [review]

**Pull request merged**
